language: python

before_install:
  - pip install poetry
  - pip install nox
# install:
#   - poetry install

jobs:
  include:
    - python: "3.6"
      env: NOXSESSION="tests-3.6"
    - python: "3.7"
      env: NOXSESSION="tests-3.7"
    - python: "3.8"
      env: NOXSESSION="tests-3.8"
    - python: "3.8"
      env: NOXSESSION="lint"
    - python: "3.8"
      env: NOXSESSION="docs"

script: nox --non-interactive --session "$NOXSESSION"

notifications:
  email: msdiallo@quantifyafrica.org
